"""HaGoKu Studio 统计护栏"""

from .statistical import (
    AssumptionsViolated,
    CleaningHighImpact,
    ConsiderPowerAnalysis,
    GuardrailResult,
    GuardrailRule,
    HighVIF,
    MissingNotRandom,
    MustDiagnoseModel,
    MustReportCI,
    MustReportEffectSize,
    NoCausalClaimWithoutMethod,
    NoConclusionWithoutTest,
    PotentialOverfitting,
    Severity,
    SmallSampleSize,
    StatisticalGuardrails,
    SuggestInteraction,
    SuggestNonlinear,
)

__all__ = [
    "AssumptionsViolated",
    "CleaningHighImpact",
    "ConsiderPowerAnalysis",
    "GuardrailResult",
    "GuardrailRule",
    "HighVIF",
    "MissingNotRandom",
    "MustDiagnoseModel",
    "MustReportCI",
    "MustReportEffectSize",
    "NoCausalClaimWithoutMethod",
    "NoConclusionWithoutTest",
    "PotentialOverfitting",
    "Severity",
    "SmallSampleSize",
    "StatisticalGuardrails",
    "SuggestInteraction",
    "SuggestNonlinear",
]
