"""HaGoKu Studio 统计护栏"""

from .parsers import (
    check_p_ci_consistency,
    deep_validate,
    detect_hallucination_indicators,
    is_valid_ci,
    is_valid_effect_size,
    is_valid_pvalue,
    parse_confidence_interval,
    parse_conclusion_count,
    parse_effect_size,
    parse_pvalue,
    validate_analysis_output,
)
from .statistical import (
    AssumptionsViolated,
    CleaningHighImpact,
    ConsiderPowerAnalysis,
    GuardrailResult,
    GuardrailRule,
    HighVIF,
    MissingNotRandom,
    MustDiagnoseModel,
    MustReportCI,
    MustReportEffectSize,
    NoCausalClaimWithoutMethod,
    NoConclusionWithoutTest,
    PotentialOverfitting,
    Severity,
    SmallSampleSize,
    StatisticalGuardrails,
    SuggestInteraction,
    SuggestNonlinear,
)

__all__ = [
    # statistical rules
    "AssumptionsViolated",
    "CleaningHighImpact",
    "ConsiderPowerAnalysis",
    "GuardrailResult",
    "GuardrailRule",
    "HighVIF",
    "MissingNotRandom",
    "MustDiagnoseModel",
    "MustReportCI",
    "MustReportEffectSize",
    "NoCausalClaimWithoutMethod",
    "NoConclusionWithoutTest",
    "PotentialOverfitting",
    "Severity",
    "SmallSampleSize",
    "StatisticalGuardrails",
    "SuggestInteraction",
    "SuggestNonlinear",
    # parsers — 提取 & 校验
    "check_p_ci_consistency",
    "deep_validate",
    "detect_hallucination_indicators",
    "is_valid_ci",
    "is_valid_effect_size",
    "is_valid_pvalue",
    "parse_confidence_interval",
    "parse_conclusion_count",
    "parse_effect_size",
    "parse_pvalue",
    "validate_analysis_output",
]
