[theme]
primaryColor = "#0891b2"
backgroundColor = "#0a0e17"
secondaryBackgroundColor = "#161b22"
textColor = "#e2e8f0"
font = "sans serif"

[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false
